server:
  port: 8081

spring:
  #security:
   # user:
    #  name: admin
     # password: admin123

  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://db:5432/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  


  #redis:
   # host: redis
    #port: 6379

  #jackson:
   # serialization:
    #  FAIL_ON_EMPTY_BEANS: false

jwt:
  secret: mySuperSecretKeyDeAlMenos32Caracteres123456
  expiration: 86400000  # 1 hora en milisegundos

logging:
  level:
  #  org.springframework: INFO
   # com.votacion.auth: DEBUG
    com.votacion.auth_service: INFO
    org.springframework.security: DEBUG
